### ISSUE TITLE
Minor: `request[backgroundTasks]: {"data":null} response: {"data":[]}` make a lot of spam 

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/ide-probe#121]
Maybe this could be skipped in the logs when data is empty?

**Comment by PawelLipski** [comment]
See e.g. https://app.circleci.com/pipelines/github/VirtusLab/git-machete-intellij-plugin/4012/workflows/2ce81c8a-09ed-4aa6-a801-926a79a1df8e/jobs/4221/parallel-runs/0/steps/0-103

**Comment by lukaszwawrzyk** [comment]
On on side seeing whole communication is good, you would know if request was sent but never returned, but on the other hand I understand that since we starred querying bg tasks through json rpc.

We should definitely reduce amount of noise in existing messages, especially don't show `{data: "<json with ugly escaped quotes>"}` and just show the actual data, perhaps in form of scala classes rather than json.
As for ignoring showing empty lists in answers, I am not yet sure how we should implement it. It might be useful information that reqiest[project/editors/all] returned an empty list for example.

**Comment by mkondratek** [comment]
WDYT about counting consistent batches of the same requests & responses? 

```
Request & response repeated <n> times:
request[backgroundTasks]: {"data":null}
response: {"data":[]}
```

**Comment by lukaszwawrzyk** [comment]
> WDYT about counting consistent batches of the same requests & responses?
> 
> ```
> Request & response repeated <n> times:
> request[backgroundTasks]: {"data":null}
> response: {"data":[]}
> ```

This is interesting, yet we would need to be at least 1 message behind with logging to know if we should show it or increment counter. There might be long running actions like build or test and you would see that build was requested after it actually completed and tests start.

**Comment by lukaszwawrzyk** [comment]
Actually, there might be a way to solve it. We could create a request/response reporter that would have a separate thread. It could accumulate repeating messages if they happen within short delay. Let's say if there is no message for 1 second, the buffer is flushed.
