### ISSUE TITLE
IntelliJ instance should be deleted after failed test  

### ISSUE THREAD

**Issue by MichalBednarz** [VirtusLab/ide-probe#22]
Each test run creates a new copy of IntelliJ instance. For now, the instance stored in `/tmp/` isn't cleaned up after the failing test. It results in a memory overflow caused by limited space in the `/tmp/` which can be resolved only by manually deleting instances or by the reboot. 

In addition, we can remove `ideprobe-workspace*` directories cause they are left empty after the test execution.

**Comment by odisseus** [comment]
I'm not sure it's a good idea to clean the environment after a failed test. The user might want to inspect it in order to find the cause of failure.

**Comment by marek1840** [comment]
> I'm not sure it's a good idea to clean the environment after a failed test. The user might want to inspect it in order to find the cause of failure.

I agree -  it makes sense. Would you, @odisseus, be willing to change the logic so that we remove the workspace and ide only after a successful or interrupted test?

Also what about CI? We don't want to hog the already limited space there. Additionally, people are potentially interested in all the failures we can get - would it make sense to delete these directories on failure only on the CI?

**Comment by odisseus** [comment]
The argument for keeping the environment of a failed test holds for the CI as well. I think it is best to keep these environments unless you are very constrained on space. Ideally, the environment of a failed test would be archived and made available for download and inspection.

I'll try to implement the cleanup logic anyway, and then we can decide when it should be invoked.

**Comment by odisseus** [comment]
Files and directories that still remain after a successful test run:
```
scala-plugin-repo3777509081734216570
ideprobe
liblz4-java4000184621870245838.so
bsp-launcher1787856568650195900
jna-1309000474
hsperfdata_virtuslab
```

**Comment by lukaszwawrzyk** [comment]
Oh, this is good to know. Most of these are out of our control, I think it is ok to leave them as they are. `ideprobe` is expected to stay, we keep cache and outputs there. 
As for `scala-plugin-repo3777509081734216570` it comes from `ScalaPluginBuilder`. It now just clones repo to temp dir, builds it there and returns the built file that lives there that I think is put in cache using ResourceProvider. We should somehow reorganize code there, so that we can delete the directory after the disted plugin is cached.
Probably you will need to do exactly the same thing for pants plugin, so when doing that you may want to also refactor this one.
